#!/usr/bin/env bash
set -Eeuo pipefail
if [[ $# -ne 18 ]]; then echo "usage: $0 DIAG_MODE LABEL START END LATERAL Z YAW0 YAW1 DURATION HOLD RATE PITCH BX BY BW BH OUTPUT EXTRA" >&2; exit 2; fi
diag_mode="$1"; label="$2"; start="$3"; end="$4"; lateral="$5"; z="$6"; yaw0="$7"; yaw1="$8"; duration="$9"; hold="${10}"; rate="${11}"; pitch="${12}"; bx="${13}"; by="${14}"; bw="${15}"; bh="${16}"; output="${17}"; extra="${18}"
script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"; stack_pid=""
[[ ! -e "${output}" ]] || { echo "refusing overwrite" >&2; exit 3; }; mkdir -p "${output}"
cleanup(){ local code=$?; trap - EXIT INT TERM; if [[ -n "${stack_pid}" ]] && kill -0 "${stack_pid}" 2>/dev/null; then kill -TERM "${stack_pid}" || true; wait "${stack_pid}" 2>/dev/null || true; fi; exit "${code}"; }; trap cleanup EXIT INT TERM
initial_x="$(python3 -c 'import math,sys; r=float(sys.argv[1]); y=float(sys.argv[2]); print(math.sqrt(r*r-y*y))' "${start}" "${lateral}")"
declare -a diagnostic_env=()
if [[ "${diag_mode}" == memory ]]; then diagnostic_env=(SWARM_RANGE_DIAGNOSTICS_WRITE_MODE=memory SWARM_RANGE_DIAGNOSTICS_MEMORY_MAX_RECORDS=512); elif [[ "${diag_mode}" == disk ]]; then diagnostic_env=(SWARM_RANGE_DIAGNOSTICS_WRITE_MODE=disk); else diagnostic_env=(SWARM_RANGE_PHYSICAL_DIAGNOSTICS_ENABLED=false); fi
dataset_mode=memory; [[ "${extra}" == disk ]] && dataset_mode=disk
env SWARM_RANGE_DATASET_DIR="${output}" SWARM_RANGE_DATASET_RUN_ID="paired_${label}" SWARM_RANGE_DATASET_TARGET_ID=UAV-02 SWARM_RANGE_DATASET_DEPTH_RATE_HZ=5.0 SWARM_RANGE_DATASET_WRITE_MODE="${dataset_mode}" SWARM_RANGE_RESIDUAL_MODE=off "${diagnostic_env[@]}" SWARM_UAV_01_MODEL_POSE="0,0,1,0,0,0" SWARM_UAV_02_MODEL_POSE="${initial_x},${lateral},${z},0,0,0" SWARM_LOG_DIR="${output}/runtime_logs" "${script_dir}/run_all.sh" >"${output}/stack_supervisor.log" 2>&1 & stack_pid=$!
deadline=$((SECONDS+60)); while ((SECONDS<deadline)); do curl -fsS --max-time 1 http://127.0.0.1:8000/health >/dev/null 2>&1 && break; kill -0 "${stack_pid}" 2>/dev/null || exit 4; sleep .5; done; curl -fsS http://127.0.0.1:8000/health >/dev/null
env PYTHONPATH="${script_dir}/.venv/lib/python3.12/site-packages" "${script_dir}/.venv/bin/python" -c 'from range_v2_r3_6a_capture import wait_for_observation_only_ready; wait_for_observation_only_ready()'
bash -c 'set -euo pipefail; source "$1"; gz service -s /world/default/set_physics --reqtype gz.msgs.Physics --reptype gz.msgs.Boolean --timeout 5000 --req "gravity {x:0 y:0 z:0}"; gz service -s /world/default/set_pose --reqtype gz.msgs.Pose --reptype gz.msgs.Boolean --timeout 5000 --req "name:\"x500_custom_0\" position{x:0 y:0 z:1} orientation{w:1}"; gz service -s /world/default/set_pose --reqtype gz.msgs.Pose --reptype gz.msgs.Boolean --timeout 5000 --req "name:\"x500_custom_1\" position{x:$2 y:$3 z:$4} orientation{w:1}"' _ /mnt/px4ssd/PX4-Autopilot/build/px4_sitl_default/rootfs/gz_env.sh "${initial_x}" "${lateral}" "${z}" >"${output}/static_environment_services.log"; sleep 2
"${script_dir}/.venv/bin/python" "${script_dir}/core_range_collection_memory_capture.py" --root "${output}" --scenario-id "${label}" --start-range-m "${start}" --end-range-m "${end}" --lateral-m "${lateral}" --target-z-m "${z}" --yaw-start-deg "${yaw0}" --yaw-end-deg "${yaw1}" --movement-duration-s "${duration}" --hold-duration-s "${hold}" --pose-update-rate-hz "${rate}" --pitch-deg "${pitch}" --bbox-x "${bx}" --bbox-y "${by}" --bbox-width "${bw}" --bbox-height "${bh}" >"${output}/driver_stdout.json"
kill -TERM "${stack_pid}" || true; wait "${stack_pid}" 2>/dev/null || true; stack_pid=""
