#!/bin/sh
# shellcheck disable=SC1090,SC2086
#
# @name Gazebo Sparrow Gimbal Dashboard
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=sparrow_gimbal}

param set-default SIM_GZ_EN 1
param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

# Gazebo FLU rotor coordinates converted to PX4 FRD around the composite CG.
param set-default CA_ROTOR0_PX  0.17140
param set-default CA_ROTOR0_PY  0.21837
param set-default CA_ROTOR0_PZ  0.03325
param set-default CA_ROTOR0_KM  0.016

param set-default CA_ROTOR1_PX -0.17140
param set-default CA_ROTOR1_PY -0.19143
param set-default CA_ROTOR1_PZ -0.03325
param set-default CA_ROTOR1_KM  0.016

param set-default CA_ROTOR2_PX  0.17140
param set-default CA_ROTOR2_PY -0.21837
param set-default CA_ROTOR2_PZ  0.03325
param set-default CA_ROTOR2_KM -0.016

param set-default CA_ROTOR3_PX -0.17140
param set-default CA_ROTOR3_PY  0.19143
param set-default CA_ROTOR3_PZ -0.03325
param set-default CA_ROTOR3_KM -0.016

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150
param set-default SIM_GZ_EC_MAX1 1400
param set-default SIM_GZ_EC_MAX2 1400
param set-default SIM_GZ_EC_MAX3 1400
param set-default SIM_GZ_EC_MAX4 1400

# The dashboard lidar raises the plant from 3.12 kg to 3.22 kg.  This 0.66
# hover value is the mass-scaled starting point and still requires SITL hover
# validation before ACTIVE CBF-RL flight.
param set-default MPC_THR_HOVER 0.66
param set-default MPC_ACC_HOR 4.0
param set-default MPC_ACC_HOR_MAX 4.0
param set-default MPC_XY_VEL_MAX 10.0
param set-default MPC_VEL_MANUAL 10.0

# Sparrow gains from the documented completed PX4 AutoTune.
param set-default MC_ROLLRATE_P 0.167565
param set-default MC_ROLLRATE_I 0.225351
param set-default MC_ROLLRATE_D 0.003103
param set-default MC_ROLL_P 5.698846
param set-default MC_PITCHRATE_P 0.169707
param set-default MC_PITCHRATE_I 0.228323
param set-default MC_PITCHRATE_D 0.003174
param set-default MC_PITCH_P 5.626944
param set-default MC_YAWRATE_P 0.172427
param set-default MC_YAWRATE_I 0.180053
param set-default MC_YAWRATE_D 0.003857
param set-default MC_YAW_P 5.538166

# Preserve the dashboard/QGroundControl gimbal output contract.
param set MNT_MODE_IN 4
param set MNT_MODE_OUT 0
param set MNT_DO_STAB 0
param set MNT_RANGE_ROLL 90
param set MNT_RANGE_PITCH 180
param set MNT_RANGE_YAW 360
param set MNT_OFF_ROLL 0
param set MNT_OFF_PITCH 45
param set MNT_OFF_YAW 0
param set SIM_GZ_SV_FUNC1 420
param set SIM_GZ_SV_FUNC2 421
param set SIM_GZ_SV_FUNC3 422
param set SIM_GZ_SV_DIS2 750
